# Generated by Django 5.2.8 on 2025-11-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.URLField(default='empty'),
        ),
    ]
